# Generated by Django 5.0.3 on 2024-04-03 05:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('Booking_item_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.BooleanField(default=False)),
                ('Review_Rating', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_ID', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('Pin_code', models.CharField(max_length=20)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Is_active', models.BooleanField(default=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Service_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Service_type', models.CharField(max_length=100)),
                ('Service_icon', models.ImageField(upload_to='service_icons/')),
                ('Service_description', models.TextField()),
                ('Service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Service_isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('ServiceCategory_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceCategory_name', models.CharField(max_length=100)),
                ('ServiceCategory_icon', models.ImageField(upload_to='Service_Category/')),
                ('ServiceCategory_isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('Technician_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Technician_name', models.CharField(max_length=35)),
                ('Technician_email', models.EmailField(max_length=254)),
                ('Technician_phone', models.CharField(max_length=20)),
                ('Technician_location', models.CharField(max_length=190)),
                ('Technician_pincode', models.CharField(max_length=10)),
                ('Technician_Password', models.CharField(max_length=100)),
                ('Technician_ID_Proof', models.CharField(max_length=150)),
                ('Technician_Service_Accept', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('locations', models.CharField(max_length=190)),
                ('pincode', models.CharField(max_length=10)),
                ('passwords', models.CharField(max_length=100)),
                ('role', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('Scheduling_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Booking_item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='We_Workers_models.bookingitem')),
            ],
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='Service_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='We_Workers_models.service'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='Technician_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='We_Workers_models.technician'),
        ),
        migrations.CreateModel(
            name='Booking_info',
            fields=[
                ('Booking_info_ID', models.AutoField(primary_key=True, serialize=False)),
                ('booking_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='We_Workers_models.bookingitem')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='We_Workers_models.user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bookingitem',
            unique_together={('Booking_item_ID', 'Service_ID')},
        ),
    ]
