# Generated by Django 5.0.3 on 2024-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('We_Workers_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='Technician_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='Technician_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
