# Generated by Django 5.0.3 on 2024-04-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('We_Workers_models', '0002_alter_technician_technician_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='Technician_ID_Proof',
            field=models.FileField(upload_to='technician_id_proof/'),
        ),
    ]
