# Generated by Django 5.0.3 on 2024-04-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('We_Workers_models', '0003_alter_technician_technician_id_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Is_active',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Pin_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city_name',
        ),
        migrations.AlterField(
            model_name='location',
            name='area_name',
            field=models.TextField(),
        ),
    ]
